### ISSUE TITLE
Repeat claim (car) requires value to be entered each time by CW

### ISSUE THREAD

**Issue by userresearcher** [ministryofjustice/apvs-asynchronous-worker#61]
After caseworker enters a value for car journey (shouldn't this be miles, not £?), subsequent claims show this as £0.00. Repeating the journey always involves the CW to put in a value, so it never auto approves.

[Issue explained here](https://docs.google.com/presentation/d/1LvwHIDa5dzJsHzx2r_LdP8y-F9XWvRSOh743pHHKHPg/edit?usp=sharing)

**Comment by tmrowe** [comment]
This is happening because when a car expense is input on the external site it's value defaults to 0 (as the value will be calculated by the APVS provider based on the claimants home address and the prison they are visiting). 

When a repeat claim is being built on the external site we currently retrieve the Cost submitted by the user for all expenses, NOT the ApprovedCost. Therefore the cost for cars is always returned as 0. 

This causes an issue in that if the claimant submitted a cost of £20 that was approved by APVS Provider as £18, the repeat claim would not be for the previously approved £18 but rather the originally submitted £20. If this £20 figure is within the variance allowed for auto approval it would pass through and be auto approved as £20 despite it having been reduced by the APVS Provider.

To resolve this we should only ever use the ApprovedCost column rather than the Cost column in out table functions called by the external site.

**Comment by userresearcher** [comment]
When a person first claims for a car journey, I believe the figure that should be shown on the summary page should be the distance in miles if this can be auto-calculated. If not, a note should appear to let the visitor know this figure will be calculated based on distance and 13p a mile, and will display on their approval email.

I don’t believe the variance would apply for a car journey because this would always be a fixed distance at a fixed rate, and the visitor will have no control over this. The difference would be if the rate was to go up or down which would result in a different £ amount, but presumably a rule would then apply to ever car journey impacted by this change.

Certainly the £ that is approved would make complete sense for repeat claims. Also in other cases where, for example, they took a taxi but the equivalent pubic transport value was used. It would make sense to allow repeat claims based on the lower agreed amount rather than  always send for manual processing, where the same lower amount would then be used each time.

Paul

**Comment by tmrowe** [comment]
Closed by pull request 274 in the External Web repository.
