### ISSUE TITLE
get-claims-pending-payment uses sumDistinct rather than sum

### ISSUE THREAD

**Issue by pwright08** [ministryofjustice/apvs-asynchronous-worker#85]
When adding the approved cost of a claim and the deduction amount, we use `sumDistinct`. This will not pick up rows with the same amount.

There is also an issue with using `sum`

**Comment by gdouglas1** [comment]
The issue is because of the extra join on the ClaimDeduction table.  If there are multiple ClaimDeductions, each ClaimExpense is returned the same number of times as the total number of ClaimDeduction records.

For example:
Consider a claim with 2 expenses (£10 and £15) and 2 deductions (£5 and £10).  Without the sumDistinct, the query will return an expense total of £70 and a deduction total of £30, because each record is returned twice

**Comment by gdouglas1** [comment]
Possible solution is to refactor the logic to get the claim deduction total into a separate function, however this may introduce performance issues since we need to perform a database call for each row returned by the main query

**Comment by pwright08** [comment]
closed by #86
